### ISSUE TITLE
Multiple requests with one connection

### ISSUE THREAD

**Issue by ghost** [alecgorge/jsonapi#226]
Hello, I have encountered an issue - when I request a single command to be executed on the server, it executes two times.

PHP File:

```
<?php
require('JSONAPI.php');

$api = new JSONAPI("127.0.0.1", 20059, "****", "******", "*******");

$argsas = array('pex user Nerolat group add VIP "" 2628000');
$api->call("runConsoleCommand", $argsas);
?>
```

Config:

```
method-whitelist:
- getPlayerLimit
- getPlayerCount
- permissions.addPlayerToGroup
- runConsoleCommand
options:
  stream_pusher:
    max_queue_age: 30
    max_queue_length: 500
  startup-delay: 2000
  port: 20059
  ip-whitelist:
  - 127.0.0.1
  log-to-console: 'false'
  log-to-file: 'true'
  salt: **************
  anyone-can-use-calladmin: 'false'
  use-new-api: false
logins:
  ***********: **************
```

---
