### ISSUE TITLE
Can not login using Craft Control App 

### ISSUE THREAD

**Issue by ntimo** [alecgorge/jsonapi#506]
Hello,
when I try to login using the craft control app I get this error. Can someone please help me thanks :)

```
[API Request] admin requested: jsonapi.users.user.permissions(["admin"]){AUTHED, NOT ALLOWED}
```

**Comment by alecgorge** [comment]
That error means the username and password is correct but that user doesn't have proper permissions to access the "jsonapi.users.user.permissions" method. Have you changed your permissions configuration?

**Comment by ntimo** [comment]
Sure, but what do I have to change?

**Comment by alecgorge** [comment]
Please post your `users.yml` and `groups.yml` file.

**Comment by ntimo** [comment]
Groups File: 

```
groups:
- name: full_control
  streams:
  - ALLOW_ALL
  methods:
  - ALLOW_ALL
- name: chat_only
  permissions:
  - view_online_player_list
  - view_map
  - view_chat
  - speak_in_chat
```

User:

```
users:
- username: admin
  password: somepw
  logging: true
  groups:
  - full_control
```
